### ISSUE TITLE
[Post list] Videos overflow on near posts with videos

### ISSUE THREAD

**Issue by NicKoehler** [LiveFastEatTrashRaccoon/RaccoonForLemmy#114]
**Describe the bug**
Videos overflow to other videos if they are close and the player is set to fit the screen

**To Reproduce**
1. Go to some community where there are a lot of videos
2. See the overflow

**Expected behavior**
Not to overflow

**Screenshots**
![Screenshot_20241120-102938.png](https://github.com/user-attachments/assets/59fe2c04-080a-4818-ac44-7c9bc95019c5)

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 15
 - Version:1.13.0

**Comment by AkesiSeli** [comment]
Thanks for the report! I'm super-happy to see you back!

This issue is definitely _not nice_ because in #108 I've made some fixes to videos precisely to solve issues like that (bounding box not calculated correctly), which entered the latest release 1.13.0 and it may precisely be the cause of the bug you're experiencing.

I'll have a look at it. 😭

**Comment by NicKoehler** [comment]
This is still the best lemmy app ❤️
